# Generated by Django 3.1.7 on 2021-04-15 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(choices=[('1', 'Team Lead'), ('2', 'Sr. Developer'), ('3', 'Jr Developer')], max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.IntegerField()),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='item',
            old_name='avilability',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='item',
            name='quantity',
        ),
        migrations.AddField(
            model_name='item',
            name='issuedate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ItemAssign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigndate', models.DateField()),
                ('returndate', models.DateField()),
                ('assignitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.item')),
                ('assignto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.employee')),
            ],
        ),
    ]
