# Generated by Django 3.1.7 on 2021-04-19 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_remove_employee_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='description',
        ),
        migrations.RemoveField(
            model_name='item',
            name='issuedate',
        ),
    ]
