# Generated by Django 3.1.7 on 2021-04-19 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_item_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='image',
        ),
    ]
