# Generated by Django 3.1.7 on 2021-04-20 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_remove_item_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemassign',
            old_name='assigndate',
            new_name='assign_date',
        ),
        migrations.RenameField(
            model_name='itemassign',
            old_name='assignitem',
            new_name='assign_item',
        ),
        migrations.RenameField(
            model_name='itemassign',
            old_name='assignto',
            new_name='assign_to',
        ),
        migrations.RenameField(
            model_name='itemassign',
            old_name='returndate',
            new_name='return_date',
        ),
    ]
