# Generated by Django 3.1.7 on 2021-04-20 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20210420_0437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemassign',
            name='assign_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='itemassign',
            name='return_date',
            field=models.DateField(null=True),
        ),
    ]
