# Generated by Django 3.1.7 on 2021-04-20 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_auto_20210420_0535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemassign',
            name='assign_date',
        ),
        migrations.RemoveField(
            model_name='itemassign',
            name='return_date',
        ),
    ]
