# Generated by Django 3.1.7 on 2021-04-21 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_auto_20210420_0618'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemassign',
            name='assign_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='itemassign',
            name='return_date',
            field=models.DateTimeField(null=True),
        ),
    ]
