# Generated by Django 3.1.7 on 2021-04-21 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_auto_20210421_0508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemassign',
            name='assign_date',
        ),
        migrations.RemoveField(
            model_name='itemassign',
            name='return_date',
        ),
    ]
