# Generated by Django 3.1.7 on 2021-04-21 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_itemassign_assign_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemassign',
            name='assign_date',
            field=models.DateTimeField(null=True),
        ),
    ]
