# Generated by Django 3.1.7 on 2021-04-21 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_auto_20210421_0609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemassign',
            name='assign_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
