# Generated by Django 3.1.7 on 2021-04-21 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_auto_20210421_0620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='designation',
            field=models.CharField(choices=[('Team Lead', 'Team Lead'), ('Sr. Developer', 'Sr. Developer'), ('Jr. Developer', 'Jr. Developer')], max_length=100),
        ),
    ]
