# Generated by Django 3.1.7 on 2021-04-22 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_auto_20210421_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemassign',
            name='assign_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
