# Generated by Django 3.1.7 on 2021-04-22 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_auto_20210422_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemassign',
            name='assign_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='itemassign',
            name='assign_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assign_item', to='product.item'),
        ),
        migrations.AlterField(
            model_name='itemassign',
            name='assign_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assign_to', to='product.employee'),
        ),
    ]
